### ISSUE TITLE
和前端怎么配合

### ISSUE THREAD

**Issue by 13653216371** [yomea/lx-doc#1]
rt，怎么才能顺利打开前后端呢，让人摸不着头脑 
![1721807788434](https://github.com/user-attachments/assets/35b60348-c41d-44bf-b994-eaf96d56efc1)

**Comment by yomea** [comment]
我看你到前端项目里提了部署的问题，我又新增了一个包含了mysql，nginx的镜像，你只要把前端项目打进docker镜像即可，涉及到的文件与脚本：
Dockerfile_whole --》Dockerfile，用于打包镜像，包含mysql，jdk，nginx环境，在本项目根目录下
lx-doc.zip --》前端项目压缩包，可以下载前端的项目进行压缩下
nginx.conf -》nginx配置文件，在本项目根目录下
my.cnf -》mysql的配置文件，在本项目根目录下
mysql_init_start.sh -》mysql的初始化与启动脚本，在本项目根目录下
doc.sql -》sql脚本，在本项目根目录下
run_in_docker_whole.sh -》 lx-doc应用的启动脚本，在本项目根目录下
application-prod.yml -》配置文件，在本项目根目录下
lx-core/target/lx-doc.jar -》  lx-doc应用 jar包
docker-build_whole.sh -》docker启动命令说明，在本项目根目录下
以前配置完全可以不做任何修改直接docker打包部署即可，注意创建 docker启动命令里的挂在目录在宿主机上存在即可

**Comment by yomea** [comment]
前端项目如果你不会打包，你可以找前端项目的维护者或者你有前端朋友，你也可以找他们帮你打包下

**Comment by 13653216371** [comment]
感谢指导，已经跑起来了

**Comment by yomea** [comment]
而且文档里写的很清楚的，前端打包的方式很简单的，你可以下载nodejs14执行npm i ，npm run build就可以了

**Comment by yomea** [comment]
ok

**Comment by Raikyou** [comment]
> 感谢指导，已经跑起来了

有现成的前后端镜像吗，或者有打包集成代码可以共享下吗。这两个前后端分离太难组在一起了，不像其他项目能直接用镜像启动该
