### ISSUE TITLE
feature 能否增加一个文件导入导出的功能

### ISSUE THREAD

**Issue by Maxtg2** [yomea/lx-doc#2]
增加一个文件导入导出的功能，感觉比较实用，辛苦大佬！

**Comment by yomea** [comment]
您说的是excel这种吧，excel目前前端实现是一个json字符串，与平时我们使用的office创建的文档的excel文件格式还是有很大差别的，理论上，只要把office弄的excel转成这里支持的json格式是可以的，但是工作量太大，更何况office的功能强大的太多，office的很多属性我们这都不支持，不好转换
