### ISSUE TITLE
使用脚本部署遇到问题

### ISSUE THREAD

**Issue by FreedomXuanyuan** [yomea/lx-doc#3]
run_no_in_docker.sh: 16: [[: not found

**Comment by yomea** [comment]
sorry！最近有点忙，有些日子没有打开github了，看你这个问题可能是解释器的问题，你把这个shell脚本的最顶上的这句
#!/bin/sh =》改成
#!/bin/bash 然后执行   bash wechat.sh

**Comment by FreedomXuanyuan** [comment]
十分感谢您的回复，问题解决了，没有使用脚本已经部署成功。

**Comment by yomea** [comment]
好的
